export const BASKET_ADD_PRODUCT = "BASKET_ADD_PRODUCT";
export const BASKET_REMOVE_PRODUCT = "BASKET_REMOVE_PRODUCT";
export const BASKET_UPDATE_PRODUCT = "BASKET_UPDATE_PRODUCT";
export const BASKET_GET_PRODUCTS = "BASKET_GET_PRODUCTS";
