export default {
    name: "Суши, роллы и удон",
    anchor: "sushi",
    items: [
      {
        name: "Канада",
        img: "/images/rolli/17.jpg",
        alt: "",
        desc: "Рис, угорь, сыр, огурец, авакадо, тобико, унаги соус",
        price: [370],
        size: null,
      },
      {
        name: "Калифорния угорь",
        img: "/images/rolli/16.jpg",
        alt: "",
        desc: "Рис, угорь, огурец, тобико, японский майонез",
        price: [370],
        size: null,
      },
      {
        name: "Калифорния лосось",
        img: "/images/rolli/15.jpg",
        alt: "",
        desc: "Рис, лосось, авокадо, тобико, японский майонез",
        price: [350],
        size: null,
      },
      {
        name: "Калифорния краб",
        img: "/images/rolli/14.jpg",
        alt: "",
        desc: "Рис, крабовые палочки, авокадо, тобико, японский майонез",
        price: [350],
        size: null,
      },
      {
        name: "Филадельфия",
        img: "/images/rolli/13.jpg",
        alt: "",
        desc: "Рис, лосось, сыр, огурец, тобико",
        price: [350],
        size: null,
      },
      {
        name: "Унаги Маки",
        img: "/images/rolli/12.jpg",
        alt: "",
        desc: "Рис, угорь, кунжут, унаги соус, нори",
        price: [210],
        size: null,
      },
      {
        name: "Тека Маки",
        img: "/images/rolli/11.jpg",
        alt: "",
        desc: "Рис, тунец, нори",
        price: [200],
        size: null,
      },
      {
        name: "Авакадо Маки",
        img: "/images/rolli/10.jpg",
        alt: "",
        desc: "Рис, авокадо, нори",
        price: [200],
        size: null,
      },
      {
        name: "Каппа Маки",
        img: "/images/rolli/9.jpg",
        alt: "",
        desc: "Рис, огурец, кунжут, нори",
        price: [100],
        size: null,
      },
      {
        name: "Сяки Маки (6 шт)",
        img: "/images/rolli/8.jpg",
        alt: "",
        desc: "Рис, лосось, нори",
        price: [200],
        size: null,
      },
      {
        name: "Дракон от шефа",
        img: "/images/rolli/dragon-for-schef.jpg",
        alt: "",
        desc: "Рис, сыр, огурец, угорь, зелёный лук, стружка тунца, тобико, нори",
        price: [350],
        size: null,
      },
      {
        name: "Банзай",
        img: "/images/rolli/banzai.jpg",
        alt: "",
        desc: "Рис, крабовые палочки, угорь, авокадо, спайси соус, нори",
        price: [370],
        size: null,
      },
      {
        name: "Самурай",
        img: "/images/rolli/samurai.jpg",
        alt: "",
        desc: "Рис, лосось, угорь, сыр, огурец, авокадо, нори",
        price: [370],
        size: null,
      },
      {
        name: "Запечённый лосось",
        img: "/images/rolli/zap-losos.jpg",
        alt: "",
        desc: "Рис, лосось, огурец, сыр филадельфия, сыр моцарелла, японский майонез, нори",
        price: [350],
        size: null,
      },
      {
        name: "Запечённый угорь",
        img: "/images/rolli/zap-ugor.jpg",
        alt: "",
        desc: "Рис, угорь, огурец, тобико, сыр моцарелла, нори, японский майонез",
        price: [350],
        size: null,
      },
      {
        name: "Суши с тобико (3шт)",
        img: "/images/rolli/7.jpg",
        alt: "",
        desc: "Рис, икра летучей рыбы",
        price: [180],
        size: null,
      },
      {
        name: "Суши с икрой (3шт)",
        img: "/images/rolli/6.jpg",
        alt: "",
        desc: "Рис, икра лосося",
        price: [180],
        size: null,
      },
      {
        name: "Суши креветка (3шт)",
        img: "/images/rolli/5.jpg",
        alt: "",
        desc: "Рис, креветка",
        price: [270],
        size: null,
      },
      {
        name: "Суши угорь (3шт)",
        img: "/images/rolli/4.jpg",
        alt: "",
        desc: "Рис, угорь",
        price: [300],
        size: null,
      },
      {
        name: "Суши тунец (3шт)",
        img: "/images/rolli/3.jpg",
        alt: "",
        desc: "Рис, тунец",
        price: [300],
        size: null,
      },
      {
        name: "Суши копченый лосось (3шт)",
        img: "/images/rolli/2.jpg",
        alt: "",
        desc: "Рис, копченый лосось",
        price: [210],
        size: null,
      },
      {
        name: "Суши лосось (3шт)",
        img: "/images/rolli/1.jpg",
        alt: "",
        desc: "Рис, лосось",
        price: [180],
        size: null,
      },
      {
        name: "Удон с курицей",
        img: "/images/rolli/udon-s-kur.jpg",
        alt: "",
        desc: "Удон, морковь, перец светофор, лук репчатый, курица, капуста, чеснок, яйцо, кабачки, масло подсолнечное, масло кунжутное ",
        price: [220],
        size: null,
      },
      {
        name: "Удон морской",
        img: "/images/rolli/udon-sea.jpg",
        alt: "",
        desc: "Удон, морковь, перец светофор, лук репчатый, морской коктейль, зелёный лук, чеснок, масло подсолнечное, масло кунжутное",
        price: [220],
        size: null,
      },
      {
        name: "Тяхан с курицей",
        img: "/images/rolli/tyahan-s-kur.jpg",
        alt: "",
        desc: "Рис, морковь, перец светофор, лук репчатый, курица, капуста, чеснок, яйцо, кабачки, масло подсолнечное, масло кунжутное",
        price: [220],
        size: null,
      },
      {
        name: "Тяхан морской",
        img: "/images/rolli/tyahan-sea.jpg",
        alt: "",
        desc: "Рис, морковь, перец светофор, лук репчатый, морской коктейль, зелёный лук, масло подсолнечное, масло кунжутное",
        price: [220],
        size: null,
      },
    ],
  };
  