export default {
    name: "Суши и роллы",
    anchor: "sushi",
    items: [
      {
        name: "Канада",
        img: "/images/rolli/17.jpg",
        alt: "",
        desc: "Рис, угорь, сыр, огурец, авакадо, тобико, унаги соус",
        price: [370],
        size: null,
      },
      {
        name: "Калифорния угорь",
        img: "/images/rolli/16.jpg",
        alt: "",
        desc: "Рис, угорь, огурец, тобико, японский майонез",
        price: [370],
        size: null,
      },
      {
        name: "Калифорния лосось",
        img: "/images/rolli/15.jpg",
        alt: "",
        desc: "Рис, лосось, авокадо, тобико, японский майонез",
        price: [350],
        size: null,
      },
      {
        name: "Калифорния краб",
        img: "/images/rolli/14.jpg",
        alt: "",
        desc: "Рис, краб, авокадо, тобико, японский майонез",
        price: [460],
        size: null,
      },
      {
        name: "Филадельфия",
        img: "/images/rolli/13.jpg",
        alt: "",
        desc: "Рис, лосось, сыр, огурец, тобико",
        price: [350],
        size: null,
      },
      {
        name: "Унаги Маки",
        img: "/images/rolli/12.jpg",
        alt: "",
        desc: "Рис, угорь, кунжут, унаги соус, нори",
        price: [210],
        size: null,
      },
      {
        name: "Тека Маки",
        img: "/images/rolli/11.jpg",
        alt: "",
        desc: "Рис, тунец, нори",
        price: [200],
        size: null,
      },
      {
        name: "Авакадо Маки",
        img: "/images/rolli/10.jpg",
        alt: "",
        desc: "Рис, авокадо, нори",
        price: [200],
        size: null,
      },
      {
        name: "Каппа Маки",
        img: "/images/rolli/9.jpg",
        alt: "",
        desc: "Рис, огурец, кунжут, нори",
        price: [100],
        size: null,
      },
      {
        name: "Сяки Маки (6 шт)",
        img: "/images/rolli/8.jpg",
        alt: "",
        desc: "Рис, лосось, нори",
        price: [200],
        size: null,
      },
      {
        name: "Суши с тобико (3шт)",
        img: "/images/rolli/7.jpg",
        alt: "",
        desc: "Рис, икра летучей рыбы",
        price: [180],
        size: null,
      },
      {
        name: "Суши с икрой (3шт)",
        img: "/images/rolli/6.jpg",
        alt: "",
        desc: "Рис, икра лосося",
        price: [180],
        size: null,
      },
      {
        name: "Суши креветка (3шт)",
        img: "/images/rolli/5.jpg",
        alt: "",
        desc: "Рис, креветка",
        price: [270],
        size: null,
      },
      {
        name: "Суши угорь (3шт)",
        img: "/images/rolli/4.jpg",
        alt: "",
        desc: "Рис, угорь",
        price: [300],
        size: null,
      },
      {
        name: "Суши тунец (3шт)",
        img: "/images/rolli/3.jpg",
        alt: "",
        desc: "Рис, тунец",
        price: [300],
        size: null,
      },
      {
        name: "Суши копченый лосось (3шт)",
        img: "/images/rolli/2.jpg",
        alt: "",
        desc: "Рис, копченый лосось",
        price: [210],
        size: null,
      },
      {
        name: "Суши лосось (3шт)",
        img: "/images/rolli/1.jpg",
        alt: "",
        desc: "Рис, лосось",
        price: [180],
        size: null,
      },
    ],
  };
  